//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synth.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BESREPORTS")]
        public string HansenReportingServer {
            get {
                return ((string)(this["HansenReportingServer"]));
            }
            set {
                this["HansenReportingServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.USP_SYNTH_GET_SANITARY_PIPES")]
        public string GetSanitaryPipesUSPName {
            get {
                return ((string)(this["GetSanitaryPipesUSPName"]));
            }
            set {
                this["GetSanitaryPipesUSPName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.USP_SYNTH_GET_STORM_DITCHES")]
        public string GetStormDitchesUSPName {
            get {
                return ((string)(this["GetStormDitchesUSPName"]));
            }
            set {
                this["GetStormDitchesUSPName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.USP_SYNTH_GET_STORM_PIPES")]
        public string GetStormPipesUSPName {
            get {
                return ((string)(this["GetStormPipesUSPName"]));
            }
            set {
                this["GetStormPipesUSPName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\CASSIO\\Modeling\\SAMaster_22\\Nodes\\mst_nodes_ac.mdb")]
        public string MasterNodesFile {
            get {
                return ((string)(this["MasterNodesFile"]));
            }
            set {
                this["MasterNodesFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\CASSIO\\Modeling\\SAMaster_22\\Links\\mst_links_ac.mdb")]
        public string MasterLinksFile {
            get {
                return ((string)(this["MasterLinksFile"]));
            }
            set {
                this["MasterLinksFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\CASSIO\\Modeling\\AGTools\\reconcile\\ADDRESS_GEOCODED.csv")]
        public string AddressName {
            get {
                return ((string)(this["AddressName"]));
            }
            set {
                this["AddressName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASM_REPORTS")]
        public string StoredProcsDB {
            get {
                return ((string)(this["StoredProcsDB"]));
            }
            set {
                this["StoredProcsDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("synth.log")]
        public string LogFile {
            get {
                return ((string)(this["LogFile"]));
            }
            set {
                this["LogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SynthFile {
            get {
                return ((string)(this["SynthFile"]));
            }
            set {
                this["SynthFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDirectory {
            get {
                return ((string)(this["LastDirectory"]));
            }
            set {
                this["LastDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DifferencesFile {
            get {
                return ((string)(this["DifferencesFile"]));
            }
            set {
                this["DifferencesFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Info")]
        public string LogSeverity {
            get {
                return ((string)(this["LogSeverity"]));
            }
            set {
                this["LogSeverity"] = value;
            }
        }
    }
}
